{% set version = '1.1.0' %}

{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-readxl
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/readxl_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/readxl/readxl_{{ version }}.tar.gz
  sha256: b63d21fc6510acb373e96deaec45e966a523ec75cbec75a089529297ed443116

build:
  merge_build_host: True  # [win]
  # If this is a new build for the same version, increment the build number.
  number: 0

  # This is required to make R link correctly on Linux.
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: covr, knitr, rmarkdown, rprojroot (>= 1.1), testthat
requirements:
  build:
    - {{ compiler('c') }}        # [not win]
    - {{ compiler('cxx') }}      # [not win]
    - {{native}}toolchain        # [win]
    - {{posix}}filesystem        # [win]
    - {{posix}}make
    - {{posix}}sed               # [win]
    - {{posix}}coreutils         # [win]
    - {{posix}}zip               # [win]

  host:
    - r-base
    - r-rcpp >=0.12.12
    - r-cellranger
    - r-tibble >=1.1

  run:
    - r-base
    - {{native}}gcc-libs         # [win]
    - r-rcpp >=0.12.12
    - r-cellranger
    - r-tibble >=1.1

test:
  commands:
    # You can put additional test commands to be run here.
    - $R -e "library('readxl')"           # [not win]
    - "\"%R%\" -e \"library('readxl')\""  # [win]

  # You can also put a file called run_test.py, run_test.sh, or run_test.bat
  # in the recipe that will be run at test time.

  # requires:
    # Put any additional test requirements here.

about:
  home: http://readxl.tidyverse.org, https://github.com/tidyverse/readxl
  license: GPL-3
  summary: Import excel files into R. Supports '.xls' via the embedded 'libxls' C library <https://github.com/evanmiller/libxls>
    and '.xlsx' via the embedded 'RapidXML' C++ library <https://rapidxml.sourceforge.net>.
    Works on Windows, Mac and Linux without external dependencies.
  license_family: GPL3

extra:
  recipe-maintainers:
    - johanneskoester
    - bgruening
    - mingwandroid

# The original CRAN metadata for this package was:

# Package: readxl
# Title: Read Excel Files
# Version: 1.1.0
# Authors@R: c( person("Hadley", "Wickham", , "hadley@rstudio.com", role = c("aut"),  comment = c(ORCID = "0000-0003-4757-117X") ), person("Jennifer", "Bryan", , "jenny@rstudio.com", role = c("aut", "cre"), comment = c(ORCID = "0000-0002-6983-2759") ), person("RStudio", role = c("cph", "fnd"), comment = "Copyright holder of all R code and all C/C++ code without explicit copyright attribution"), person("Marcin", "Kalicinski", role = c("ctb", "cph"), comment = "Author of included RapidXML code"), person("Komarov Valery", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("Christophe Leitienne", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("Bob Colbert", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("David Hoerl", role = c("ctb", "cph"), comment = "Author of included libxls code"), person("Evan Miller", role = c("ctb", "cph"), comment = "Author of included libxls code") )
# Description: Import excel files into R. Supports '.xls' via the embedded 'libxls' C library <https://github.com/evanmiller/libxls> and '.xlsx' via the embedded 'RapidXML' C++ library <https://rapidxml.sourceforge.net>. Works on Windows, Mac and Linux without external dependencies.
# License: GPL-3
# LazyData: true
# LinkingTo: Rcpp
# Imports: cellranger, Rcpp (>= 0.12.12), tibble (>= 1.1)
# Suggests: covr, knitr, rmarkdown, rprojroot (>= 1.1), testthat
# URL: http://readxl.tidyverse.org, https://github.com/tidyverse/readxl
# BugReports: https://github.com/tidyverse/readxl/issues
# VignetteBuilder: knitr
# RoxygenNote: 6.0.1.9000
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2018-04-19 17:27:26 UTC; jenny
# Author: Hadley Wickham [aut] (<https://orcid.org/0000-0003-4757-117X>), Jennifer Bryan [aut, cre] (<https://orcid.org/0000-0002-6983-2759>), RStudio [cph, fnd] (Copyright holder of all R code and all C/C++ code without explicit copyright attribution), Marcin Kalicinski [ctb, cph] (Author of included RapidXML code), Komarov Valery [ctb, cph] (Author of included libxls code), Christophe Leitienne [ctb, cph] (Author of included libxls code), Bob Colbert [ctb, cph] (Author of included libxls code), David Hoerl [ctb, cph] (Author of included libxls code), Evan Miller [ctb, cph] (Author of included libxls code)
# Maintainer: Jennifer Bryan <jenny@rstudio.com>
# Repository: CRAN
# Date/Publication: 2018-04-20 03:53:22 UTC

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
