travis:
  secure:
    BINSTAR_TOKEN: JbQsmkZBqcxnOlUCQfyZsqeJ2VvJ1Zqep91IbiXAAdesCUg/+ryx4nRcKRvELdfUMTvZOIPTtsSBu3ja8H09WTWtkoa5w9AbyWeV4DT601hf8ZNJ5leeLJWWq8M4NTKQz676G7NbNMrO+u67VAOezto3znPESsBPXdVfYxYITsUMj7CXSnAXK5aJEM9/nAESnW0OEshmDLwOVrwxtLfSPjpTTqxJf7wNxM4hNhtwaCe8SaXqRb/NZT8jYGZ97MDATida+LY8MYN1Pwyjd+DAmBE+sGNNTJOCisfUs7CUvTg88yKueysQWlHSBCWh5UAIr5LvrJ1wzyeoGhIl93384teZa0FwoS7209OjEHzcMnz8xja8KS16no2Z2nyqu4PxlUhCAxx6kmM8RWyuNYpuqwE4icn+LVy7LCTRGOrgqCE4raUD/vy3wJ4IVZoeWUg0E+QqEblxbvU6AiBWzDpMqO05gqbuEu9Va0O+4rXF1qoXX+biWGz+XptjfjHzj1PwBmg/mYcLJ0qWl+PQ659G3g+CPVx3wQPUOM/4Li2oC4jmEZRVCqJzCxUOjiv63CNbrudKFYp2tHrLhSait2+DhVr7wl2MQgDKbYmClPdziuFqLyGZtEaQntPzxMlozPp93Wnnoq6JHCZARJmfJbEFa+KKHQFJ9dwGlHzpQRYz2/U=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
