travis:
  secure:
    BINSTAR_TOKEN: loC4GIQGvx+dwhzodRUPfv0oi6o+y1JmMURDhqPUL7Aon9xTixPthH0k5OIvtGydfOVaM5EhU+lvD4YB1BN0DyNozpHJYpqaFbOeaexOyxYUNv9R6t5vqEGRaMMbYc79XojbuzW+RjXz/HH9rSRsN6JWBlMJxki4/p5SfpT7KDknEitDML1sj6HiNDy7OL5GGa2YsIf2hOTiGWFRpWY/a9fsqe/hxXdwmn7w5bxzLV58jdGhs0OVtuilwMAJ8U7X0s0J3nvsp/jz9qdDtC2V7ENUc8h/7rAlpuDfHD5mxq1DE07eJZstplA0ULFhvL+qdU0n6VBd2ylhQZ81/5kNbNUBwMQ1dK+9Y6XSg7/jBo2lINemVVWFQFQftd1U7BowUj2b4ahTjbmYASOS6bIt1MlGj26kZT7MKAN8eYPdUvhzCl/X0sip4kBPfZpsnJIVjy+tXW1cT74KLWXP99tDiKqQNIGxPcQkH2Jlmm3eKSP0n38ND2zMnP97Qer3gavIHOu3ubVTWVLHznWtyFE197tnaA7INrJkeB8HWIa6sB/3/4WoICgEY0r83SUb3MW62fCXPGWYIVtzuFnJvVmjmXzpLfMnLkx9KP4RyjhKRNYknZ1y/OxD3Gft6UDCvyQqG4qhwEqaFTsCHX8i9jnhGaygvF4s0hG5PRkpBhVzp7w=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
