travis:
  secure:
    BINSTAR_TOKEN: WV3duoEmfDoGocubzIFsUYCeHLebPKPt9mVgTvyPqNV3AJpSWvOkHVwMmYDQpITElkUjbnZ3uW2FSnox1jhlL9lhYPXywR0ZOO+2ZhdV1QWpaiR/2zEGtXGQmvqIJCb9tf9+FKBhr/t+jUSB+6MQz6nPzT0fWWNpbwBz5KmVDiVLMaroQj3MEGVC4TFC1qRhV1XZC/a2E1/7wjJPPQRIcrZyz6hwohA0/AeFfFLoLfixKGRRHGvya4T4xTdQfF455CcjlpMjwz4qxxdxdTOnTQdRhCHX2LIoGBCG0tBI5XEHqUTe4cCJcKzqEVOk+EecBkGs9NLmA/gsze2nh+J8KkG6BbK9QSkV31glgIyPQsvh23qALiBeM2H65T/BLVFHg10p1SaAMTEPxSGURzA3C+zJHqn4RO6TJ9KEXov5QrUtmy+5PLmIGZvpifL3uLA05wKqzYE4yB0QaMsC6hIK4MQwt9gAXlZ1sw/MJrKylu3zuOldy08q8Fa2e9DkPL2r8Iw7cAIKv1smU/REjwpp1Lvh0A0eK+0ds/vOZGFzGIWSQqH8ka+Oo+uy+p0hIv9rO6ebqXELx9bEyqIEb+U5YSxPF1GGM1Qslhu8wZ7gStji0ct+qHwccF1EiyLPyHNB6ISRaR7JTO8heQcPrxjCtu3kuJOR1fpI6I133POAUck=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
