travis:
  secure:
    BINSTAR_TOKEN: obpB/sQUqb4YXaEmHil3PLehghZ9nm4IFS9U+lGlTBqET/Tnw+1Pb6tPltcfN3FLquV8znYQGacULUXIzPWIAqMdfKiSsRTw9GTov4SiRc1esR2syG/pupECE4JPqCZLn/jLxsZyiVwUxz+h5RdZHMnNj652xY936NIXyJq1m0FkZkCAYj/XbogHqd5WUl0GxHIXXgdAbyu6hla5fHYuFFM2T3vxYnHzutwN/Ee1yM/LPjwykCRq64p5ZvUmLhnYJBWw1WFlMQu8ZmBBLOQxA9e0H8kq/2AgxAO5122J8ceKztsieop+N6JzpbY2CsxIS2d9SaL42ZGve8m9cKFpBAsY0kp8woACCUUIjTX+w89ORgJQOIJe++rIkA/u8Pd/Cnjqq9lr5GcO+2gXGFB/7yrVvWsDdU5EwY4Iyl78VrXL0+m4TQNJXuyCoGdYoqy7SyUXJI85XmtBAYzS72w1d++/hmIRi3H9ElbJrRj1LQ8Jyjc+moT1dXvJdKOsECWO22YXS5FMK/GgTfo7UnIyNcl94inpoifXkGm4o6fyIIKFZCf5vI6B5wkYioN7s0pWug+kFORSohtnL9HgmhnD2MRmHc2eieBiwpsMh2JtOCamU9w/U2tyMtAGv1cK7aUHvJaCXuZxOg2no+WQZfOMrLJpLtHsh+cNAx+J0MmPb8E=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
